		.equ FT245_STAT,	0x8000
		.equ FT245_DATA,	0x8001

		.equ FT245_RXF,		0x01
		.equ FT245_TXE,		0x02

		.equ LCD_12864_REG, 	0x8200
		.equ LCD_12864_DATA, 	0x8201

		.equ VIA_orb,		0x8300
		.equ VIA_ora,		0x8301
		.equ VIA_ddrb,		0x8302
		.equ VIA_ddra,		0x8303
		.equ VIA_t1cl,		0x8304
		.equ VIA_t1ch,		0x8305
		.equ VIA_t1ll,		0x8306
		.equ VIA_t1lh,		0x8307
		.equ VIA_t2cl,		0x8308
		.equ VIA_t2ch,		0x8309
		.equ VIA_sr,		0x830A
		.equ VIA_acr,		0x830B
		.equ VIA_pcr,		0x830C
		.equ VIA_ifr,		0x830D
		.equ VIA_ier,		0x830E
		.equ VIA_ora_nh,	0x830F

